package org.opensrp.service;

import org.apache.commons.lang3.StringUtils;
import org.joda.time.DateTime;
import org.opensrp.domain.Manifest;
import org.opensrp.repository.ManifestRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

@Service
public class ManifestService {

    private static Logger logger = LoggerFactory.getLogger(ManifestService.class.toString());

    private ManifestRepository manifestRepository;

    @Autowired
    public void setManifestRepository(ManifestRepository manifestRepository) {
        this.manifestRepository = manifestRepository;
    }
    public ManifestRepository getManifestRepository() {
        return manifestRepository;
    }

    public List<Manifest> getAllManifest() {
        return manifestRepository.getAll();
    }

    public void addOrUpdateManifest(Manifest manifest) {
        manifest.setUpdatedAt(new Date());
        if (manifestRepository.get(String.valueOf(manifest.getId())) != null) {
            manifestRepository.update(manifest);
        } else {
            manifest.setCreatedAt(new Date());
            manifestRepository.add(manifest);
        }
    }

    public Manifest addManifest(Manifest manifest) {
        if (manifest.getId() != 0)
            throw new IllegalArgumentException("Manifest.id should not be specified but generated by the database");

        manifest.setCreatedAt(new Date());
        manifest.setUpdatedAt(new Date());
        manifestRepository.add(manifest);
        return manifest;

    }

    public Manifest updateManifest(Manifest manifest) {
        if (manifest.getId() == 0)
            throw new IllegalArgumentException("Id not specified");

        manifest.setUpdatedAt(new Date());
        manifestRepository.update(manifest);
        return manifest;
    }

    public Manifest getManifest(int id) {
        if (id == 0)
            return null;

        return getManifestRepository().get(String.valueOf(id));
    }

    public Set<String> saveManifests(List<Manifest> manifests) {
        Set<String> manifestWithErrors = new HashSet<>();
        for (Manifest manifest : manifests) {
            try {
                addOrUpdateManifest(manifest);
            } catch (Exception e) {
                logger.error(e.getMessage(), e);
                manifestWithErrors.add(String.valueOf(manifest.getId()));
            }
        }

        return manifestWithErrors;
    }


    public void deleteManifest(Manifest manifest) {
        if (manifest.getId() == 0) {
            throw new IllegalArgumentException("Identifier not specified");
        }

        manifestRepository.safeRemove(manifest);
    }

    public Manifest getManifestByAppId(String appId) {
        if (StringUtils.isBlank(appId))
            return null;

        return manifestRepository.getManifestByAppId(appId);
    }
}
