package org.opensrp.repository.postgres.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.CampaignMetadata;
import org.opensrp.domain.postgres.CampaignMetadataExample;

public interface CampaignMetadataMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    long countByExample(CampaignMetadataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int deleteByExample(CampaignMetadataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int insert(CampaignMetadata record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int insertSelective(CampaignMetadata record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    List<CampaignMetadata> selectByExample(CampaignMetadataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    CampaignMetadata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int updateByExampleSelective(@Param("record") CampaignMetadata record,
                                 @Param("example") CampaignMetadataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int updateByExample(@Param("record") CampaignMetadata record, @Param("example") CampaignMetadataExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int updateByPrimaryKeySelective(CampaignMetadata record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table core.campaign_metadata
     *
     * @mbg.generated Fri Nov 09 12:47:47 EAT 2018
     */
    int updateByPrimaryKey(CampaignMetadata record);
}