package org.opensrp.repository.postgres.mapper;

import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ClientForm;
import org.opensrp.domain.postgres.ClientFormExample;

import java.util.List;

public interface ClientFormMapper {

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	long countByExample(ClientFormExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int deleteByExample(ClientFormExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int insert(ClientForm record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int insertSelective(ClientForm record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	List<ClientForm> selectByExample(ClientFormExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	ClientForm selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int updateByExampleSelective(@Param("record") ClientForm record, @Param("example") ClientFormExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int updateByExample(@Param("record") ClientForm record, @Param("example") ClientFormExample example);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int updateByPrimaryKeySelective(ClientForm record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	int updateByPrimaryKey(ClientForm record);
}
