package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ClientFormExample;
import org.opensrp.domain.postgres.ClientForm;

public interface ClientFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    long countByExample(ClientFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int deleteByExample(ClientFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int insert(ClientForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int insertSelective(ClientForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    List<ClientForm> selectByExample(ClientFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    ClientForm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int updateByExampleSelective(@Param("record") ClientForm record, @Param("example") ClientFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int updateByExample(@Param("record") ClientForm record, @Param("example") ClientFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int updateByPrimaryKeySelective(ClientForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_forms
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    int updateByPrimaryKey(ClientForm record);
}