package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.ClientMigrationFile;
import org.opensrp.domain.postgres.ClientMigrationFileExample;

public interface ClientMigrationFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    long countByExample(ClientMigrationFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int deleteByExample(ClientMigrationFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int insert(ClientMigrationFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int insertSelective(ClientMigrationFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    List<ClientMigrationFile> selectByExample(ClientMigrationFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    ClientMigrationFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int updateByExampleSelective(@Param("record") ClientMigrationFile record, @Param("example") ClientMigrationFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int updateByExample(@Param("record") ClientMigrationFile record, @Param("example") ClientMigrationFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int updateByPrimaryKeySelective(ClientMigrationFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    int updateByPrimaryKey(ClientMigrationFile record);
}