package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.Location;
import org.opensrp.domain.postgres.LocationExample;

public interface LocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    long countByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int deleteByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int insert(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int insertSelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    List<Location> selectByExample(LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    Location selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByExampleSelective(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByExample(@Param("record") Location record, @Param("example") LocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByPrimaryKeySelective(Location record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.location
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByPrimaryKey(Location record);
}