package org.opensrp.repository.postgres.mapper;

import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.Organization;
import org.opensrp.domain.postgres.OrganizationExample;

import java.util.List;

public interface OrganizationMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    long countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int insert(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int insertSelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    Organization selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int updateByExampleSelective(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int updateByExample(@Param("record") Organization record, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int updateByPrimaryKeySelective(Organization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    int updateByPrimaryKey(Organization record);
}
