package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.OrganizationLocation;
import org.opensrp.domain.postgres.OrganizationLocationExample;

public interface OrganizationLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    long countByExample(OrganizationLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int deleteByExample(OrganizationLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int insert(OrganizationLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int insertSelective(OrganizationLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    List<OrganizationLocation> selectByExample(OrganizationLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int updateByExampleSelective(@Param("record") OrganizationLocation record, @Param("example") OrganizationLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.organization_location
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int updateByExample(@Param("record") OrganizationLocation record, @Param("example") OrganizationLocationExample example);
}