package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.PlanProcessingStatus;
import org.opensrp.domain.postgres.PlanProcessingStatusExample;

public interface PlanProcessingStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    long countByExample(PlanProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int deleteByExample(PlanProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int insert(PlanProcessingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int insertSelective(PlanProcessingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    List<PlanProcessingStatus> selectByExample(PlanProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    PlanProcessingStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int updateByExampleSelective(@Param("record") PlanProcessingStatus record, @Param("example") PlanProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int updateByExample(@Param("record") PlanProcessingStatus record, @Param("example") PlanProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int updateByPrimaryKeySelective(PlanProcessingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.plan_processing_status
     *
     * @mbg.generated Sat Sep 11 11:04:03 EAT 2021
     */
    int updateByPrimaryKey(PlanProcessingStatus record);
}