package org.opensrp.repository.postgres.mapper;

import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.PractitionerRole;
import org.opensrp.domain.postgres.PractitionerRoleExample;

import java.util.List;

public interface PractitionerRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    long countByExample(PractitionerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int deleteByExample(PractitionerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int insert(PractitionerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int insertSelective(PractitionerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    List<PractitionerRole> selectByExample(PractitionerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    PractitionerRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int updateByExampleSelective(@Param("record") PractitionerRole record, @Param("example") PractitionerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int updateByExample(@Param("record") PractitionerRole record, @Param("example") PractitionerRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int updateByPrimaryKeySelective(PractitionerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team.practitioner_role
     *
     * @mbg.generated Fri Aug 30 16:08:23 EAT 2019
     */
    int updateByPrimaryKey(PractitionerRole record);
}