package org.opensrp.repository.postgres.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.SettingsMetadata;
import org.opensrp.domain.postgres.SettingsMetadataExample;

public interface SettingsMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    long countByExample(SettingsMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int deleteByExample(SettingsMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int insert(SettingsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int insertSelective(SettingsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    List<SettingsMetadata> selectByExample(SettingsMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    SettingsMetadata selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int updateByExampleSelective(@Param("record") SettingsMetadata record, @Param("example") SettingsMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int updateByExample(@Param("record") SettingsMetadata record, @Param("example") SettingsMetadataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int updateByPrimaryKeySelective(SettingsMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.settings_metadata
     *
     * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
     */
    int updateByPrimaryKey(SettingsMetadata record);
}