package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.SmsApiProcessingStatus;
import org.opensrp.domain.postgres.SmsApiProcessingStatusExample;

public interface SmsApiProcessingStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    long countByExample(SmsApiProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int deleteByExample(SmsApiProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int insert(SmsApiProcessingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int insertSelective(SmsApiProcessingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    List<SmsApiProcessingStatus> selectByExample(SmsApiProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    SmsApiProcessingStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int updateByExampleSelective(@Param("record") SmsApiProcessingStatus record, @Param("example") SmsApiProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int updateByExample(@Param("record") SmsApiProcessingStatus record, @Param("example") SmsApiProcessingStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int updateByPrimaryKeySelective(SmsApiProcessingStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.sms_api_processing_status
     *
     * @mbg.generated Thu Apr 01 20:22:39 EAT 2021
     */
    int updateByPrimaryKey(SmsApiProcessingStatus record);
}