package org.opensrp.repository.postgres.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.opensrp.domain.postgres.Structure;
import org.opensrp.domain.postgres.StructureExample;

public interface StructureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    long countByExample(StructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int deleteByExample(StructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int insert(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int insertSelective(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    List<Structure> selectByExample(StructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    Structure selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByExampleSelective(@Param("record") Structure record, @Param("example") StructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByExample(@Param("record") Structure record, @Param("example") StructureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByPrimaryKeySelective(Structure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.structure
     *
     * @mbg.generated Thu Nov 15 15:55:07 EAT 2018
     */
    int updateByPrimaryKey(Structure record);
}
