package org.opensrp.domain.postgres;

import java.util.Date;

public class ClientFormMetadata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.id
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.identifier
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.jurisdiction
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private String jurisdiction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.version
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.label
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.module
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.client_form_metadata.created_at
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.id
     *
     * @return the value of core.client_form_metadata.id
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.id
     *
     * @param id the value for core.client_form_metadata.id
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.identifier
     *
     * @return the value of core.client_form_metadata.identifier
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.identifier
     *
     * @param identifier the value for core.client_form_metadata.identifier
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.jurisdiction
     *
     * @return the value of core.client_form_metadata.jurisdiction
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public String getJurisdiction() {
        return jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.jurisdiction
     *
     * @param jurisdiction the value for core.client_form_metadata.jurisdiction
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setJurisdiction(String jurisdiction) {
        this.jurisdiction = jurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.version
     *
     * @return the value of core.client_form_metadata.version
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.version
     *
     * @param version the value for core.client_form_metadata.version
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.label
     *
     * @return the value of core.client_form_metadata.label
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.label
     *
     * @param label the value for core.client_form_metadata.label
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.module
     *
     * @return the value of core.client_form_metadata.module
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.module
     *
     * @param module the value for core.client_form_metadata.module
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.client_form_metadata.created_at
     *
     * @return the value of core.client_form_metadata.created_at
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.client_form_metadata.created_at
     *
     * @param createdAt the value for core.client_form_metadata.created_at
     *
     * @mbg.generated Fri Aug 16 14:03:07 EAT 2019
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}