package org.opensrp.domain.postgres;

import java.util.Date;

public class ClientMetadata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.client_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private Long clientId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.document_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String documentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.base_entity_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String baseEntityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.relational_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String relationalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.server_version
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private Long serverVersion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.openmrs_uuid
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String openmrsUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.unique_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String uniqueId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.first_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.middle_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String middleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.last_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.birth_date
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private Date birthDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.date_deleted
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private Date dateDeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.residence
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	private String residence;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.location_id
	 * @mbg.generated  Mon Jun 29 12:32:42 PKT 2020
	 */
	private String locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.client_metadata.client_type
	 * @mbg.generated  Mon Jun 29 12:32:42 PKT 2020
	 */
	private String clientType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.id
	 * @return  the value of core.client_metadata.id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.id
	 * @param id  the value for core.client_metadata.id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.client_id
	 * @return  the value of core.client_metadata.client_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public Long getClientId() {
		return clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.client_id
	 * @param clientId  the value for core.client_metadata.client_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setClientId(Long clientId) {
		this.clientId = clientId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.document_id
	 * @return  the value of core.client_metadata.document_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getDocumentId() {
		return documentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.document_id
	 * @param documentId  the value for core.client_metadata.document_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.base_entity_id
	 * @return  the value of core.client_metadata.base_entity_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getBaseEntityId() {
		return baseEntityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.base_entity_id
	 * @param baseEntityId  the value for core.client_metadata.base_entity_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setBaseEntityId(String baseEntityId) {
		this.baseEntityId = baseEntityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.relational_id
	 * @return  the value of core.client_metadata.relational_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getRelationalId() {
		return relationalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.relational_id
	 * @param relationalId  the value for core.client_metadata.relational_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setRelationalId(String relationalId) {
		this.relationalId = relationalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.server_version
	 * @return  the value of core.client_metadata.server_version
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public Long getServerVersion() {
		return serverVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.server_version
	 * @param serverVersion  the value for core.client_metadata.server_version
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setServerVersion(Long serverVersion) {
		this.serverVersion = serverVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.openmrs_uuid
	 * @return  the value of core.client_metadata.openmrs_uuid
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getOpenmrsUuid() {
		return openmrsUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.openmrs_uuid
	 * @param openmrsUuid  the value for core.client_metadata.openmrs_uuid
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setOpenmrsUuid(String openmrsUuid) {
		this.openmrsUuid = openmrsUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.unique_id
	 * @return  the value of core.client_metadata.unique_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getUniqueId() {
		return uniqueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.unique_id
	 * @param uniqueId  the value for core.client_metadata.unique_id
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.first_name
	 * @return  the value of core.client_metadata.first_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.first_name
	 * @param firstName  the value for core.client_metadata.first_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.middle_name
	 * @return  the value of core.client_metadata.middle_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getMiddleName() {
		return middleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.middle_name
	 * @param middleName  the value for core.client_metadata.middle_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.last_name
	 * @return  the value of core.client_metadata.last_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.last_name
	 * @param lastName  the value for core.client_metadata.last_name
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.birth_date
	 * @return  the value of core.client_metadata.birth_date
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public Date getBirthDate() {
		return birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.birth_date
	 * @param birthDate  the value for core.client_metadata.birth_date
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.date_deleted
	 * @return  the value of core.client_metadata.date_deleted
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public Date getDateDeleted() {
		return dateDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.date_deleted
	 * @param dateDeleted  the value for core.client_metadata.date_deleted
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setDateDeleted(Date dateDeleted) {
		this.dateDeleted = dateDeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.residence
	 * @return  the value of core.client_metadata.residence
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public String getResidence() {
		return residence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.residence
	 * @param residence  the value for core.client_metadata.residence
	 * @mbg.generated  Tue Apr 30 18:07:16 EAT 2019
	 */
	public void setResidence(String residence) {
		this.residence = residence;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.location_id
	 * @return  the value of core.client_metadata.location_id
	 * @mbg.generated  Mon Jun 29 12:32:42 PKT 2020
	 */
	public String getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.location_id
	 * @param locationId  the value for core.client_metadata.location_id
	 * @mbg.generated  Mon Jun 29 12:32:42 PKT 2020
	 */
	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.client_metadata.client_type
	 * @return  the value of core.client_metadata.client_type
	 * @mbg.generated  Mon Jun 29 12:32:42 PKT 2020
	 */
	public String getClientType() {
		return clientType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.client_metadata.client_type
	 * @param clientType  the value for core.client_metadata.client_type
	 * @mbg.generated  Mon Jun 29 12:32:42 PKT 2020
	 */
	public void setClientType(String clientType) {
		this.clientType = clientType;
	}
}
