package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClientFormMetadataExample {

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public ClientFormMetadataExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	protected abstract static class GeneratedCriteria {

		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new IllegalArgumentException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new IllegalArgumentException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new IllegalArgumentException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdentifierIsNull() {
			addCriterion("identifier is null");
			return (Criteria) this;
		}

		public Criteria andIdentifierIsNotNull() {
			addCriterion("identifier is not null");
			return (Criteria) this;
		}

		public Criteria andIdentifierEqualTo(String value) {
			addCriterion("identifier =", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierNotEqualTo(String value) {
			addCriterion("identifier <>", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierGreaterThan(String value) {
			addCriterion("identifier >", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierGreaterThanOrEqualTo(String value) {
			addCriterion("identifier >=", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierLessThan(String value) {
			addCriterion("identifier <", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierLessThanOrEqualTo(String value) {
			addCriterion("identifier <=", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierLike(String value) {
			addCriterion("identifier like", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierNotLike(String value) {
			addCriterion("identifier not like", value, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierIn(List<String> values) {
			addCriterion("identifier in", values, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierNotIn(List<String> values) {
			addCriterion("identifier not in", values, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierBetween(String value1, String value2) {
			addCriterion("identifier between", value1, value2, "identifier");
			return (Criteria) this;
		}

		public Criteria andIdentifierNotBetween(String value1, String value2) {
			addCriterion("identifier not between", value1, value2, "identifier");
			return (Criteria) this;
		}

		public Criteria andJurisdictionIsNull() {
			addCriterion("jurisdiction is null");
			return (Criteria) this;
		}

		public Criteria andJurisdictionIsNotNull() {
			addCriterion("jurisdiction is not null");
			return (Criteria) this;
		}

		public Criteria andJurisdictionEqualTo(String value) {
			addCriterion("jurisdiction =", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionNotEqualTo(String value) {
			addCriterion("jurisdiction <>", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionGreaterThan(String value) {
			addCriterion("jurisdiction >", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionGreaterThanOrEqualTo(String value) {
			addCriterion("jurisdiction >=", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionLessThan(String value) {
			addCriterion("jurisdiction <", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionLessThanOrEqualTo(String value) {
			addCriterion("jurisdiction <=", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionLike(String value) {
			addCriterion("jurisdiction like", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionNotLike(String value) {
			addCriterion("jurisdiction not like", value, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionIn(List<String> values) {
			addCriterion("jurisdiction in", values, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionNotIn(List<String> values) {
			addCriterion("jurisdiction not in", values, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionBetween(String value1, String value2) {
			addCriterion("jurisdiction between", value1, value2, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andJurisdictionNotBetween(String value1, String value2) {
			addCriterion("jurisdiction not between", value1, value2, "jurisdiction");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(String value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(String value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(String value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(String value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(String value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(String value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLike(String value) {
			addCriterion("version like", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotLike(String value) {
			addCriterion("version not like", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<String> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<String> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(String value1, String value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(String value1, String value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andLabelIsNull() {
			addCriterion("label is null");
			return (Criteria) this;
		}

		public Criteria andLabelIsNotNull() {
			addCriterion("label is not null");
			return (Criteria) this;
		}

		public Criteria andLabelEqualTo(String value) {
			addCriterion("label =", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotEqualTo(String value) {
			addCriterion("label <>", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelGreaterThan(String value) {
			addCriterion("label >", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelGreaterThanOrEqualTo(String value) {
			addCriterion("label >=", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLessThan(String value) {
			addCriterion("label <", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLessThanOrEqualTo(String value) {
			addCriterion("label <=", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLike(String value) {
			addCriterion("label like", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotLike(String value) {
			addCriterion("label not like", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelIn(List<String> values) {
			addCriterion("label in", values, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotIn(List<String> values) {
			addCriterion("label not in", values, "label");
			return (Criteria) this;
		}

		public Criteria andLabelBetween(String value1, String value2) {
			addCriterion("label between", value1, value2, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotBetween(String value1, String value2) {
			addCriterion("label not between", value1, value2, "label");
			return (Criteria) this;
		}

		public Criteria andModuleIsNull() {
			addCriterion("module is null");
			return (Criteria) this;
		}

		public Criteria andModuleIsNotNull() {
			addCriterion("module is not null");
			return (Criteria) this;
		}

		public Criteria andModuleEqualTo(String value) {
			addCriterion("module =", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleNotEqualTo(String value) {
			addCriterion("module <>", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleGreaterThan(String value) {
			addCriterion("module >", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleGreaterThanOrEqualTo(String value) {
			addCriterion("module >=", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleLessThan(String value) {
			addCriterion("module <", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleLessThanOrEqualTo(String value) {
			addCriterion("module <=", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleLike(String value) {
			addCriterion("module like", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleNotLike(String value) {
			addCriterion("module not like", value, "module");
			return (Criteria) this;
		}

		public Criteria andModuleIn(List<String> values) {
			addCriterion("module in", values, "module");
			return (Criteria) this;
		}

		public Criteria andModuleNotIn(List<String> values) {
			addCriterion("module not in", values, "module");
			return (Criteria) this;
		}

		public Criteria andModuleBetween(String value1, String value2) {
			addCriterion("module between", value1, value2, "module");
			return (Criteria) this;
		}

		public Criteria andModuleNotBetween(String value1, String value2) {
			addCriterion("module not between", value1, value2, "module");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNull() {
			addCriterion("created_at is null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIsNotNull() {
			addCriterion("created_at is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedAtEqualTo(Date value) {
			addCriterion("created_at =", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotEqualTo(Date value) {
			addCriterion("created_at <>", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThan(Date value) {
			addCriterion("created_at >", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
			addCriterion("created_at >=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThan(Date value) {
			addCriterion("created_at <", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
			addCriterion("created_at <=", value, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtIn(List<Date> values) {
			addCriterion("created_at in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotIn(List<Date> values) {
			addCriterion("created_at not in", values, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtBetween(Date value1, Date value2) {
			addCriterion("created_at between", value1, value2, "createdAt");
			return (Criteria) this;
		}

		public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
			addCriterion("created_at not between", value1, value2, "createdAt");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated do_not_delete_during_merge Fri Mar 20 12:11:34 EAT 2020
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table core.client_form_metadata
	 *
	 * @mbg.generated Fri Mar 20 12:11:34 EAT 2020
	 */
	public static class Criterion {

		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}
