package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClientMigrationFileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public ClientMigrationFileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new IllegalArgumentException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new IllegalArgumentException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new IllegalArgumentException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNull() {
            addCriterion("identifier is null");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNotNull() {
            addCriterion("identifier is not null");
            return (Criteria) this;
        }

        public Criteria andIdentifierEqualTo(String value) {
            addCriterion("identifier =", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotEqualTo(String value) {
            addCriterion("identifier <>", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThan(String value) {
            addCriterion("identifier >", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("identifier >=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThan(String value) {
            addCriterion("identifier <", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThanOrEqualTo(String value) {
            addCriterion("identifier <=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLike(String value) {
            addCriterion("identifier like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotLike(String value) {
            addCriterion("identifier not like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierIn(List<String> values) {
            addCriterion("identifier in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotIn(List<String> values) {
            addCriterion("identifier not in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierBetween(String value1, String value2) {
            addCriterion("identifier between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotBetween(String value1, String value2) {
            addCriterion("identifier not between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNull() {
            addCriterion("filename is null");
            return (Criteria) this;
        }

        public Criteria andFilenameIsNotNull() {
            addCriterion("filename is not null");
            return (Criteria) this;
        }

        public Criteria andFilenameEqualTo(String value) {
            addCriterion("filename =", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotEqualTo(String value) {
            addCriterion("filename <>", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThan(String value) {
            addCriterion("filename >", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameGreaterThanOrEqualTo(String value) {
            addCriterion("filename >=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThan(String value) {
            addCriterion("filename <", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLessThanOrEqualTo(String value) {
            addCriterion("filename <=", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameLike(String value) {
            addCriterion("filename like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotLike(String value) {
            addCriterion("filename not like", value, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameIn(List<String> values) {
            addCriterion("filename in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotIn(List<String> values) {
            addCriterion("filename not in", values, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameBetween(String value1, String value2) {
            addCriterion("filename between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andFilenameNotBetween(String value1, String value2) {
            addCriterion("filename not between", value1, value2, "filename");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageIsNull() {
            addCriterion("on_object_storage is null");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageIsNotNull() {
            addCriterion("on_object_storage is not null");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageEqualTo(Boolean value) {
            addCriterion("on_object_storage =", value, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageNotEqualTo(Boolean value) {
            addCriterion("on_object_storage <>", value, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageGreaterThan(Boolean value) {
            addCriterion("on_object_storage >", value, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageGreaterThanOrEqualTo(Boolean value) {
            addCriterion("on_object_storage >=", value, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageLessThan(Boolean value) {
            addCriterion("on_object_storage <", value, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageLessThanOrEqualTo(Boolean value) {
            addCriterion("on_object_storage <=", value, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageIn(List<Boolean> values) {
            addCriterion("on_object_storage in", values, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageNotIn(List<Boolean> values) {
            addCriterion("on_object_storage not in", values, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageBetween(Boolean value1, Boolean value2) {
            addCriterion("on_object_storage between", value1, value2, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andOnObjectStorageNotBetween(Boolean value1, Boolean value2) {
            addCriterion("on_object_storage not between", value1, value2, "onObjectStorage");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathIsNull() {
            addCriterion("object_storage_path is null");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathIsNotNull() {
            addCriterion("object_storage_path is not null");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathEqualTo(String value) {
            addCriterion("object_storage_path =", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathNotEqualTo(String value) {
            addCriterion("object_storage_path <>", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathGreaterThan(String value) {
            addCriterion("object_storage_path >", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathGreaterThanOrEqualTo(String value) {
            addCriterion("object_storage_path >=", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathLessThan(String value) {
            addCriterion("object_storage_path <", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathLessThanOrEqualTo(String value) {
            addCriterion("object_storage_path <=", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathLike(String value) {
            addCriterion("object_storage_path like", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathNotLike(String value) {
            addCriterion("object_storage_path not like", value, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathIn(List<String> values) {
            addCriterion("object_storage_path in", values, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathNotIn(List<String> values) {
            addCriterion("object_storage_path not in", values, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathBetween(String value1, String value2) {
            addCriterion("object_storage_path between", value1, value2, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andObjectStoragePathNotBetween(String value1, String value2) {
            addCriterion("object_storage_path not between", value1, value2, "objectStoragePath");
            return (Criteria) this;
        }

        public Criteria andJurisdictionIsNull() {
            addCriterion("jurisdiction is null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionIsNotNull() {
            addCriterion("jurisdiction is not null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionEqualTo(String value) {
            addCriterion("jurisdiction =", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNotEqualTo(String value) {
            addCriterion("jurisdiction <>", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionGreaterThan(String value) {
            addCriterion("jurisdiction >", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionGreaterThanOrEqualTo(String value) {
            addCriterion("jurisdiction >=", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionLessThan(String value) {
            addCriterion("jurisdiction <", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionLessThanOrEqualTo(String value) {
            addCriterion("jurisdiction <=", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionLike(String value) {
            addCriterion("jurisdiction like", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNotLike(String value) {
            addCriterion("jurisdiction not like", value, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionIn(List<String> values) {
            addCriterion("jurisdiction in", values, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNotIn(List<String> values) {
            addCriterion("jurisdiction not in", values, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionBetween(String value1, String value2) {
            addCriterion("jurisdiction between", value1, value2, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNotBetween(String value1, String value2) {
            addCriterion("jurisdiction not between", value1, value2, "jurisdiction");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andManifestIdIsNull() {
            addCriterion("manifest_id is null");
            return (Criteria) this;
        }

        public Criteria andManifestIdIsNotNull() {
            addCriterion("manifest_id is not null");
            return (Criteria) this;
        }

        public Criteria andManifestIdEqualTo(Integer value) {
            addCriterion("manifest_id =", value, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdNotEqualTo(Integer value) {
            addCriterion("manifest_id <>", value, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdGreaterThan(Integer value) {
            addCriterion("manifest_id >", value, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("manifest_id >=", value, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdLessThan(Integer value) {
            addCriterion("manifest_id <", value, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdLessThanOrEqualTo(Integer value) {
            addCriterion("manifest_id <=", value, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdIn(List<Integer> values) {
            addCriterion("manifest_id in", values, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdNotIn(List<Integer> values) {
            addCriterion("manifest_id not in", values, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdBetween(Integer value1, Integer value2) {
            addCriterion("manifest_id between", value1, value2, "manifestId");
            return (Criteria) this;
        }

        public Criteria andManifestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("manifest_id not between", value1, value2, "manifestId");
            return (Criteria) this;
        }

        public Criteria andFileContentsIsNull() {
            addCriterion("file_contents is null");
            return (Criteria) this;
        }

        public Criteria andFileContentsIsNotNull() {
            addCriterion("file_contents is not null");
            return (Criteria) this;
        }

        public Criteria andFileContentsEqualTo(String value) {
            addCriterion("file_contents =", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsNotEqualTo(String value) {
            addCriterion("file_contents <>", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsGreaterThan(String value) {
            addCriterion("file_contents >", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsGreaterThanOrEqualTo(String value) {
            addCriterion("file_contents >=", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsLessThan(String value) {
            addCriterion("file_contents <", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsLessThanOrEqualTo(String value) {
            addCriterion("file_contents <=", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsLike(String value) {
            addCriterion("file_contents like", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsNotLike(String value) {
            addCriterion("file_contents not like", value, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsIn(List<String> values) {
            addCriterion("file_contents in", values, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsNotIn(List<String> values) {
            addCriterion("file_contents not in", values, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsBetween(String value1, String value2) {
            addCriterion("file_contents between", value1, value2, "fileContents");
            return (Criteria) this;
        }

        public Criteria andFileContentsNotBetween(String value1, String value2) {
            addCriterion("file_contents not between", value1, value2, "fileContents");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.client_migration_file
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 08 12:11:26 EAT 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table core.client_migration_file
     *
     * @mbg.generated Mon Feb 08 12:11:26 EAT 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
