package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.List;

public class LocationTagExample {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	protected String orderByClause;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	protected boolean distinct;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	protected List<Criteria> oredCriteria;
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public LocationTagExample() {
		oredCriteria = new ArrayList<Criteria>();
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}
	
	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	protected abstract static class GeneratedCriteria {
		
		protected List<Criterion> criteria;
		
		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}
		
		public boolean isValid() {
			return criteria.size() > 0;
		}
		
		public List<Criterion> getAllCriteria() {
			return criteria;
		}
		
		public List<Criterion> getCriteria() {
			return criteria;
		}
		
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new IllegalArgumentException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}
		
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new IllegalArgumentException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}
		
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new IllegalArgumentException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}
		
		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}
		
		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}
		
		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}
		
		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}
		
		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}
		
		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}
		
		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}
		
		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}
		
		public Criteria andActiveIsNull() {
			addCriterion("active is null");
			return (Criteria) this;
		}
		
		public Criteria andActiveIsNotNull() {
			addCriterion("active is not null");
			return (Criteria) this;
		}
		
		public Criteria andActiveEqualTo(Boolean value) {
			addCriterion("active =", value, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveNotEqualTo(Boolean value) {
			addCriterion("active <>", value, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveGreaterThan(Boolean value) {
			addCriterion("active >", value, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveGreaterThanOrEqualTo(Boolean value) {
			addCriterion("active >=", value, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveLessThan(Boolean value) {
			addCriterion("active <", value, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveLessThanOrEqualTo(Boolean value) {
			addCriterion("active <=", value, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveIn(List<Boolean> values) {
			addCriterion("active in", values, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveNotIn(List<Boolean> values) {
			addCriterion("active not in", values, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveBetween(Boolean value1, Boolean value2) {
			addCriterion("active between", value1, value2, "active");
			return (Criteria) this;
		}
		
		public Criteria andActiveNotBetween(Boolean value1, Boolean value2) {
			addCriterion("active not between", value1, value2, "active");
			return (Criteria) this;
		}
	}
	
	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table
	 * core.location_tag
	 * 
	 * @mbggenerated Sun Mar 08 18:18:51 BDT 2020
	 */
	public static class Criterion {
		
		private String condition;
		
		private Object value;
		
		private Object secondValue;
		
		private boolean noValue;
		
		private boolean singleValue;
		
		private boolean betweenValue;
		
		private boolean listValue;
		
		private String typeHandler;
		
		public String getCondition() {
			return condition;
		}
		
		public Object getValue() {
			return value;
		}
		
		public Object getSecondValue() {
			return secondValue;
		}
		
		public boolean isNoValue() {
			return noValue;
		}
		
		public boolean isSingleValue() {
			return singleValue;
		}
		
		public boolean isBetweenValue() {
			return betweenValue;
		}
		
		public boolean isListValue() {
			return listValue;
		}
		
		public String getTypeHandler() {
			return typeHandler;
		}
		
		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}
		
		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}
		
		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}
		
		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}
		
		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
	
	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table
	 * core.location_tag
	 *
	 * @mbggenerated do_not_delete_during_merge Sun Mar 08 16:30:00 BDT 2020
	 */
	public static class Criteria extends GeneratedCriteria {
		
		protected Criteria() {
			super();
		}
	}
}
