package org.opensrp.domain.postgres;

public class Manifest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.manifest.id
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.manifest.json
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    private Object json;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.manifest.app_version
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    private String appVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.manifest.app_id
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.manifest.created_at
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.manifest.updated_at
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    private Long updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.manifest.id
     *
     * @return the value of core.manifest.id
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.manifest.id
     *
     * @param id the value for core.manifest.id
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.manifest.json
     *
     * @return the value of core.manifest.json
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public Object getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.manifest.json
     *
     * @param json the value for core.manifest.json
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public void setJson(Object json) {
        this.json = json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.manifest.app_version
     *
     * @return the value of core.manifest.app_version
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.manifest.app_version
     *
     * @param appVersion the value for core.manifest.app_version
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.manifest.app_id
     *
     * @return the value of core.manifest.app_id
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.manifest.app_id
     *
     * @param appId the value for core.manifest.app_id
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.manifest.created_at
     *
     * @return the value of core.manifest.created_at
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.manifest.created_at
     *
     * @param createdAt the value for core.manifest.created_at
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.manifest.updated_at
     *
     * @return the value of core.manifest.updated_at
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.manifest.updated_at
     *
     * @param updatedAt the value for core.manifest.updated_at
     *
     * @mbg.generated Thu Oct 03 10:25:41 EAT 2019
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }
}