package org.opensrp.domain.postgres;

import java.util.Date;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.identifier
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.active
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Boolean active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.name
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.type
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Object type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.date_deleted
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Date dateDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.parent_id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.date_created
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.date_edited
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Date dateEdited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.organization.server_version
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Long serverVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.id
     *
     * @return the value of team.organization.id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.id
     *
     * @param id the value for team.organization.id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.identifier
     *
     * @return the value of team.organization.identifier
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.identifier
     *
     * @param identifier the value for team.organization.identifier
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.active
     *
     * @return the value of team.organization.active
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.active
     *
     * @param active the value for team.organization.active
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.name
     *
     * @return the value of team.organization.name
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.name
     *
     * @param name the value for team.organization.name
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.type
     *
     * @return the value of team.organization.type
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Object getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.type
     *
     * @param type the value for team.organization.type
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setType(Object type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.date_deleted
     *
     * @return the value of team.organization.date_deleted
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Date getDateDeleted() {
        return dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.date_deleted
     *
     * @param dateDeleted the value for team.organization.date_deleted
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.parent_id
     *
     * @return the value of team.organization.parent_id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.parent_id
     *
     * @param parentId the value for team.organization.parent_id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.date_created
     *
     * @return the value of team.organization.date_created
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.date_created
     *
     * @param dateCreated the value for team.organization.date_created
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.date_edited
     *
     * @return the value of team.organization.date_edited
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Date getDateEdited() {
        return dateEdited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.date_edited
     *
     * @param dateEdited the value for team.organization.date_edited
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setDateEdited(Date dateEdited) {
        this.dateEdited = dateEdited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.organization.server_version
     *
     * @return the value of team.organization.server_version
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Long getServerVersion() {
        return serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.organization.server_version
     *
     * @param serverVersion the value for team.organization.server_version
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setServerVersion(Long serverVersion) {
        this.serverVersion = serverVersion;
    }
}