package org.opensrp.domain.postgres;

import java.util.Date;

public class PlanMetadata extends PlanMetadataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.plan_metadata.plan_id
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    private Long planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.plan_metadata.created_at
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.plan_metadata.updated_at
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.plan_metadata.plan_id
     *
     * @return the value of core.plan_metadata.plan_id
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    public Long getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.plan_metadata.plan_id
     *
     * @param planId the value for core.plan_metadata.plan_id
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    public void setPlanId(Long planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.plan_metadata.created_at
     *
     * @return the value of core.plan_metadata.created_at
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.plan_metadata.created_at
     *
     * @param createdAt the value for core.plan_metadata.created_at
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.plan_metadata.updated_at
     *
     * @return the value of core.plan_metadata.updated_at
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.plan_metadata.updated_at
     *
     * @param updatedAt the value for core.plan_metadata.updated_at
     *
     * @mbg.generated Mon Sep 28 14:57:00 EAT 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}