package org.opensrp.domain.postgres;

public class PlanMetadata extends PlanMetadataKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core.plan_metadata.is_deleted
     *
     * @mbg.generated Fri May 03 16:46:46 EAT 2019
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core.plan_metadata.is_deleted
     *
     * @return the value of core.plan_metadata.is_deleted
     *
     * @mbg.generated Fri May 03 16:46:46 EAT 2019
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core.plan_metadata.is_deleted
     *
     * @param isDeleted the value for core.plan_metadata.is_deleted
     *
     * @mbg.generated Fri May 03 16:46:46 EAT 2019
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}