package org.opensrp.domain.postgres;

import java.util.Date;

public class Practitioner {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.identifier
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private String identifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.active
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Boolean active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.name
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.user_id
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.username
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.date_deleted
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Date dateDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.date_created
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.date_edited
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Date dateEdited;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.practitioner.server_version
     *
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    private Long serverVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.id
     *
     * @return the value of team.practitioner.id
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.id
     *
     * @param id the value for team.practitioner.id
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.identifier
     *
     * @return the value of team.practitioner.identifier
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.identifier
     *
     * @param identifier the value for team.practitioner.identifier
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.active
     *
     * @return the value of team.practitioner.active
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Boolean getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.active
     *
     * @param active the value for team.practitioner.active
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.name
     *
     * @return the value of team.practitioner.name
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.name
     *
     * @param name the value for team.practitioner.name
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.user_id
     *
     * @return the value of team.practitioner.user_id
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.user_id
     *
     * @param userId the value for team.practitioner.user_id
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.username
     *
     * @return the value of team.practitioner.username
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.username
     *
     * @param username the value for team.practitioner.username
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.date_deleted
     *
     * @return the value of team.practitioner.date_deleted
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Date getDateDeleted() {
        return dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.date_deleted
     *
     * @param dateDeleted the value for team.practitioner.date_deleted
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setDateDeleted(Date dateDeleted) {
        this.dateDeleted = dateDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.date_created
     *
     * @return the value of team.practitioner.date_created
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.date_created
     *
     * @param dateCreated the value for team.practitioner.date_created
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.date_edited
     *
     * @return the value of team.practitioner.date_edited
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Date getDateEdited() {
        return dateEdited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.date_edited
     *
     * @param dateEdited the value for team.practitioner.date_edited
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setDateEdited(Date dateEdited) {
        this.dateEdited = dateEdited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.practitioner.server_version
     *
     * @return the value of team.practitioner.server_version
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public Long getServerVersion() {
        return serverVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.practitioner.server_version
     *
     * @param serverVersion the value for team.practitioner.server_version
     * @mbg.generated Mon Dec 06 14:53:20 EAT 2021
     */
    public void setServerVersion(Long serverVersion) {
        this.serverVersion = serverVersion;
    }
}
