package org.opensrp.domain.postgres;

import java.util.ArrayList;
import java.util.List;

public class SettingsMetadataExampleGeneratedCriteria {

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table core.settings_metadata
	 *
	 * @mbg.generated Fri Apr 24 10:25:50 EAT 2020
	 */
	protected abstract static class GeneratedCriteria {

		protected List<SettingsMetadataExample.Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<SettingsMetadataExample.Criterion> getAllCriteria() {
			return criteria;
		}

		public List<SettingsMetadataExample.Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				try {
					throw new IllegalArgumentException("Value for condition cannot be null");
				}
				catch (IllegalArgumentException e) {
					e.printStackTrace();
				}
			}
			criteria.add(new SettingsMetadataExample.Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				try {
					throw new IllegalArgumentException("Value for " + property + " cannot be null");
				}
				catch (IllegalArgumentException e) {
					e.printStackTrace();
				}
			}
			criteria.add(new SettingsMetadataExample.Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				try {
					throw new IllegalArgumentException("Between values for " + property + " cannot be null");
				}
				catch (IllegalArgumentException e) {
					e.printStackTrace();
				}
			}
			criteria.add(new SettingsMetadataExample.Criterion(condition, value1, value2));
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdIsNull() {
			addCriterion("sm.id is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdIsNotNull() {
			addCriterion("sm.id is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdEqualTo(Long value) {
			addCriterion("sm.id =", value, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdNotEqualTo(Long value) {
			addCriterion("sm.id <>", value, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdGreaterThan(Long value) {
			addCriterion("sm.id >", value, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sm.id >=", value, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdLessThan(Long value) {
			addCriterion("sm.id <", value, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("sm.id <=", value, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdIn(List<Long> values) {
			addCriterion("sm.id in", values, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdNotIn(List<Long> values) {
			addCriterion("sm.id not in", values, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("sm.id between", value1, value2, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("sm.id not between", value1, value2, "id");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdIsNull() {
			addCriterion("settings_id is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdIsNotNull() {
			addCriterion("settings_id is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdEqualTo(Long value) {
			addCriterion("settings_id =", value, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdNotEqualTo(Long value) {
			addCriterion("settings_id <>", value, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdGreaterThan(Long value) {
			addCriterion("settings_id >", value, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdGreaterThanOrEqualTo(Long value) {
			addCriterion("settings_id >=", value, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdLessThan(Long value) {
			addCriterion("settings_id <", value, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdLessThanOrEqualTo(Long value) {
			addCriterion("settings_id <=", value, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdIn(List<Long> values) {
			addCriterion("settings_id in", values, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdNotIn(List<Long> values) {
			addCriterion("settings_id not in", values, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdBetween(Long value1, Long value2) {
			addCriterion("settings_id between", value1, value2, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingsIdNotBetween(Long value1, Long value2) {
			addCriterion("settings_id not between", value1, value2, "settingsId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdIsNull() {
			addCriterion("document_id is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdIsNotNull() {
			addCriterion("document_id is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdEqualTo(String value) {
			addCriterion("document_id =", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdNotEqualTo(String value) {
			addCriterion("document_id <>", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdGreaterThan(String value) {
			addCriterion("document_id >", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdGreaterThanOrEqualTo(String value) {
			addCriterion("document_id >=", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdLessThan(String value) {
			addCriterion("document_id <", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdLessThanOrEqualTo(String value) {
			addCriterion("document_id <=", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdLike(String value) {
			addCriterion("document_id like", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdNotLike(String value) {
			addCriterion("document_id not like", value, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdIn(List<String> values) {
			addCriterion("document_id in", values, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdNotIn(List<String> values) {
			addCriterion("document_id not in", values, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdBetween(String value1, String value2) {
			addCriterion("document_id between", value1, value2, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andDocumentIdNotBetween(String value1, String value2) {
			addCriterion("document_id not between", value1, value2, "documentId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierIsNull() {
			addCriterion("identifier is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierIsNotNull() {
			addCriterion("identifier is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierEqualTo(String value) {
			addCriterion("identifier =", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierNotEqualTo(String value) {
			addCriterion("identifier <>", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierGreaterThan(String value) {
			addCriterion("identifier >", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierGreaterThanOrEqualTo(String value) {
			addCriterion("identifier >=", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierLessThan(String value) {
			addCriterion("identifier <", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierLessThanOrEqualTo(String value) {
			addCriterion("identifier <=", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierLike(String value) {
			addCriterion("identifier like", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierNotLike(String value) {
			addCriterion("identifier not like", value, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierIn(List<String> values) {
			addCriterion("identifier in", values, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierNotIn(List<String> values) {
			addCriterion("identifier not in", values, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierBetween(String value1, String value2) {
			addCriterion("identifier between", value1, value2, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andIdentifierNotBetween(String value1, String value2) {
			addCriterion("identifier not between", value1, value2, "identifier");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionIsNull() {
			addCriterion("server_version is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionIsNotNull() {
			addCriterion("server_version is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionEqualTo(Long value) {
			addCriterion("server_version =", value, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionNotEqualTo(Long value) {
			addCriterion("server_version <>", value, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionGreaterThan(Long value) {
			addCriterion("server_version >", value, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionGreaterThanOrEqualTo(Long value) {
			addCriterion("server_version >=", value, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionLessThan(Long value) {
			addCriterion("server_version <", value, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionLessThanOrEqualTo(Long value) {
			addCriterion("server_version <=", value, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionIn(List<Long> values) {
			addCriterion("server_version in", values, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionNotIn(List<Long> values) {
			addCriterion("server_version not in", values, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionBetween(Long value1, Long value2) {
			addCriterion("server_version between", value1, value2, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andServerVersionNotBetween(Long value1, Long value2) {
			addCriterion("server_version not between", value1, value2, "serverVersion");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIsNull() {
			addCriterion("team is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIsNotNull() {
			addCriterion("team is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamEqualTo(String value) {
			addCriterion("team =", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamNotEqualTo(String value) {
			addCriterion("team <>", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamGreaterThan(String value) {
			addCriterion("team >", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamGreaterThanOrEqualTo(String value) {
			addCriterion("team >=", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamLessThan(String value) {
			addCriterion("team <", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamLessThanOrEqualTo(String value) {
			addCriterion("team <=", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamLike(String value) {
			addCriterion("team like", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamNotLike(String value) {
			addCriterion("team not like", value, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIn(List<String> values) {
			addCriterion("team in", values, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamNotIn(List<String> values) {
			addCriterion("team not in", values, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamBetween(String value1, String value2) {
			addCriterion("team between", value1, value2, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamNotBetween(String value1, String value2) {
			addCriterion("team not between", value1, value2, "team");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdIsNull() {
			addCriterion("team_id is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdIsNotNull() {
			addCriterion("team_id is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdEqualTo(String value) {
			addCriterion("team_id =", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdNotEqualTo(String value) {
			addCriterion("team_id <>", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdGreaterThan(String value) {
			addCriterion("team_id >", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdGreaterThanOrEqualTo(String value) {
			addCriterion("team_id >=", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdLessThan(String value) {
			addCriterion("team_id <", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdLessThanOrEqualTo(String value) {
			addCriterion("team_id <=", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdLike(String value) {
			addCriterion("team_id like", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdNotLike(String value) {
			addCriterion("team_id not like", value, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdIn(List<String> values) {
			addCriterion("team_id in", values, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdNotIn(List<String> values) {
			addCriterion("team_id not in", values, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdBetween(String value1, String value2) {
			addCriterion("team_id between", value1, value2, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andTeamIdNotBetween(String value1, String value2) {
			addCriterion("team_id not between", value1, value2, "teamId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdIsNull() {
			addCriterion("provider_id is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdIsNotNull() {
			addCriterion("provider_id is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdEqualTo(String value) {
			addCriterion("provider_id =", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdNotEqualTo(String value) {
			addCriterion("provider_id <>", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdGreaterThan(String value) {
			addCriterion("provider_id >", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdGreaterThanOrEqualTo(String value) {
			addCriterion("provider_id >=", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdLessThan(String value) {
			addCriterion("provider_id <", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdLessThanOrEqualTo(String value) {
			addCriterion("provider_id <=", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdLike(String value) {
			addCriterion("provider_id like", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdNotLike(String value) {
			addCriterion("provider_id not like", value, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdIn(List<String> values) {
			addCriterion("provider_id in", values, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdNotIn(List<String> values) {
			addCriterion("provider_id not in", values, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdBetween(String value1, String value2) {
			addCriterion("provider_id between", value1, value2, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andProviderIdNotBetween(String value1, String value2) {
			addCriterion("provider_id not between", value1, value2, "providerId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdIsNull() {
			addCriterion("location_id is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdIsNotNull() {
			addCriterion("location_id is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdEqualTo(String value) {
			addCriterion("location_id =", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdNotEqualTo(String value) {
			addCriterion("location_id <>", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdGreaterThan(String value) {
			addCriterion("location_id >", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdGreaterThanOrEqualTo(String value) {
			addCriterion("location_id >=", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdLessThan(String value) {
			addCriterion("location_id <", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdLessThanOrEqualTo(String value) {
			addCriterion("location_id <=", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdLike(String value) {
			addCriterion("location_id like", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdNotLike(String value) {
			addCriterion("location_id not like", value, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdIn(List<String> values) {
			addCriterion("location_id in", values, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdNotIn(List<String> values) {
			addCriterion("location_id not in", values, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdBetween(String value1, String value2) {
			addCriterion("location_id between", value1, value2, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andLocationIdNotBetween(String value1, String value2) {
			addCriterion("location_id not between", value1, value2, "locationId");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidIsNull() {
			addCriterion("uuid is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidIsNotNull() {
			addCriterion("uuid is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidEqualTo(String value) {
			addCriterion("uuid =", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidNotEqualTo(String value) {
			addCriterion("uuid <>", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidGreaterThan(String value) {
			addCriterion("uuid >", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidGreaterThanOrEqualTo(String value) {
			addCriterion("uuid >=", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidLessThan(String value) {
			addCriterion("uuid <", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidLessThanOrEqualTo(String value) {
			addCriterion("uuid <=", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidLike(String value) {
			addCriterion("uuid like", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidNotLike(String value) {
			addCriterion("uuid not like", value, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidIn(List<String> values) {
			addCriterion("uuid in", values, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidNotIn(List<String> values) {
			addCriterion("uuid not in", values, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidBetween(String value1, String value2) {
			addCriterion("uuid between", value1, value2, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andUuidNotBetween(String value1, String value2) {
			addCriterion("uuid not between", value1, value2, "uuid");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonIsNull() {
			addCriterion("json is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonIsNotNull() {
			addCriterion("json is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonEqualTo(Object value) {
			addCriterion("json =", value, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonNotEqualTo(Object value) {
			addCriterion("json <>", value, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonGreaterThan(Object value) {
			addCriterion("json >", value, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonGreaterThanOrEqualTo(Object value) {
			addCriterion("json >=", value, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonLessThan(Object value) {
			addCriterion("json <", value, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonLessThanOrEqualTo(Object value) {
			addCriterion("json <=", value, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonIn(List<Object> values) {
			addCriterion("json in", values, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonNotIn(List<Object> values) {
			addCriterion("json not in", values, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonBetween(Object value1, Object value2) {
			addCriterion("json between", value1, value2, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andJsonNotBetween(Object value1, Object value2) {
			addCriterion("json not between", value1, value2, "json");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeIsNull() {
			addCriterion("setting_type is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeIsNotNull() {
			addCriterion("setting_type is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeEqualTo(String value) {
			addCriterion("setting_type =", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeNotEqualTo(String value) {
			addCriterion("setting_type <>", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeGreaterThan(String value) {
			addCriterion("setting_type >", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeGreaterThanOrEqualTo(String value) {
			addCriterion("setting_type >=", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeLessThan(String value) {
			addCriterion("setting_type <", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeLessThanOrEqualTo(String value) {
			addCriterion("setting_type <=", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeLike(String value) {
			addCriterion("setting_type like", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeNotLike(String value) {
			addCriterion("setting_type not like", value, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeIn(List<String> values) {
			addCriterion("setting_type in", values, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeNotIn(List<String> values) {
			addCriterion("setting_type not in", values, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeBetween(String value1, String value2) {
			addCriterion("setting_type between", value1, value2, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingTypeNotBetween(String value1, String value2) {
			addCriterion("setting_type not between", value1, value2, "settingType");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueIsNull() {
			addCriterion("setting_value is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueIsNotNull() {
			addCriterion("setting_value is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueEqualTo(String value) {
			addCriterion("setting_value =", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueNotEqualTo(String value) {
			addCriterion("setting_value <>", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueGreaterThan(String value) {
			addCriterion("setting_value >", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueGreaterThanOrEqualTo(String value) {
			addCriterion("setting_value >=", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueLessThan(String value) {
			addCriterion("setting_value <", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueLessThanOrEqualTo(String value) {
			addCriterion("setting_value <=", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueLike(String value) {
			addCriterion("setting_value like", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueNotLike(String value) {
			addCriterion("setting_value not like", value, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueIn(List<String> values) {
			addCriterion("setting_value in", values, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueNotIn(List<String> values) {
			addCriterion("setting_value not in", values, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueBetween(String value1, String value2) {
			addCriterion("setting_value between", value1, value2, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingValueNotBetween(String value1, String value2) {
			addCriterion("setting_value not between", value1, value2, "settingValue");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyIsNull() {
			addCriterion("setting_key is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyIsNotNull() {
			addCriterion("setting_key is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyEqualTo(String value) {
			addCriterion("setting_key =", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyNotEqualTo(String value) {
			addCriterion("setting_key <>", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyGreaterThan(String value) {
			addCriterion("setting_key >", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyGreaterThanOrEqualTo(String value) {
			addCriterion("setting_key >=", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyLessThan(String value) {
			addCriterion("setting_key <", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyLessThanOrEqualTo(String value) {
			addCriterion("setting_key <=", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyLike(String value) {
			addCriterion("setting_key like", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyNotLike(String value) {
			addCriterion("setting_key not like", value, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyIn(List<String> values) {
			addCriterion("setting_key in", values, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyNotIn(List<String> values) {
			addCriterion("setting_key not in", values, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyBetween(String value1, String value2) {
			addCriterion("setting_key between", value1, value2, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingKeyNotBetween(String value1, String value2) {
			addCriterion("setting_key not between", value1, value2, "settingKey");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionIsNull() {
			addCriterion("setting_description is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionIsNotNull() {
			addCriterion("setting_description is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionEqualTo(String value) {
			addCriterion("setting_description =", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionNotEqualTo(String value) {
			addCriterion("setting_description <>", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionGreaterThan(String value) {
			addCriterion("setting_description >", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("setting_description >=", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionLessThan(String value) {
			addCriterion("setting_description <", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionLessThanOrEqualTo(String value) {
			addCriterion("setting_description <=", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionLike(String value) {
			addCriterion("setting_description like", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionNotLike(String value) {
			addCriterion("setting_description not like", value, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionIn(List<String> values) {
			addCriterion("setting_description in", values, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionNotIn(List<String> values) {
			addCriterion("setting_description not in", values, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionBetween(String value1, String value2) {
			addCriterion("setting_description between", value1, value2, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andSettingDescriptionNotBetween(String value1,
				String value2) {
			addCriterion("setting_description not between", value1, value2, "settingDescription");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelIsNull() {
			addCriterion("setting_label is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelIsNotNull() {
			addCriterion("setting_label is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelEqualTo(String value) {
			addCriterion("setting_label =", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelNotEqualTo(String value) {
			addCriterion("setting_label <>", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelGreaterThan(String value) {
			addCriterion("setting_label >", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelGreaterThanOrEqualTo(String value) {
			addCriterion("setting_label >=", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelLessThan(String value) {
			addCriterion("setting_label <", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelLessThanOrEqualTo(String value) {
			addCriterion("setting_label <=", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelLike(String value) {
			addCriterion("setting_label like", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelNotLike(String value) {
			addCriterion("setting_label not like", value, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelIn(List<String> values) {
			addCriterion("setting_label in", values, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelNotIn(List<String> values) {
			addCriterion("setting_label not in", values, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelBetween(String value1, String value2) {
			addCriterion("setting_label between", value1, value2, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andsettingLabelNotBetween(String value1, String value2) {
			addCriterion("setting_label not between", value1, value2, "settingLabel");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromIsNull() {
			addCriterion("inherited_from is null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromIsNotNull() {
			addCriterion("inherited_from is not null");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromEqualTo(String value) {
			addCriterion("inherited_from =", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromNotEqualTo(String value) {
			addCriterion("inherited_from <>", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromGreaterThan(String value) {
			addCriterion("inherited_from >", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromGreaterThanOrEqualTo(String value) {
			addCriterion("inherited_from >=", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromLessThan(String value) {
			addCriterion("inherited_from <", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromLessThanOrEqualTo(String value) {
			addCriterion("inherited_from <=", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromLike(String value) {
			addCriterion("inherited_from like", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromNotLike(String value) {
			addCriterion("inherited_from not like", value, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromIn(List<String> values) {
			addCriterion("inherited_from in", values, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromNotIn(List<String> values) {
			addCriterion("inherited_from not in", values, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromBetween(String value1, String value2) {
			addCriterion("inherited_from between", value1, value2, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}

		public SettingsMetadataExampleGeneratedCriteria.Criteria andInheritedFromNotBetween(String value1, String value2) {
			addCriterion("inherited_from not between", value1, value2, "inheritedFrom");
			return (SettingsMetadataExampleGeneratedCriteria.Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator.
	 * This class corresponds to the database table core.settings_metadata
	 *
	 * @mbg.generated do_not_delete_during_merge Fri Apr 24 10:25:50 EAT 2020
	 */
	public static class Criteria extends SettingsMetadataExampleGeneratedCriteria.GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

}
