package org.opensrp.domain.postgres;

public class TaskMetadata {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.id
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.task_id
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private Long taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private String identifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.campaign_identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private String campaignIdentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.group_identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private String groupIdentifier;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.for_entity
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private String forEntity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column core.task_metadata.server_version
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	private Long serverVersion;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.id
	 * @return  the value of core.task_metadata.id
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.id
	 * @param id  the value for core.task_metadata.id
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.task_id
	 * @return  the value of core.task_metadata.task_id
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public Long getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.task_id
	 * @param taskId  the value for core.task_metadata.task_id
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setTaskId(Long taskId) {
		this.taskId = taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.identifier
	 * @return  the value of core.task_metadata.identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public String getIdentifier() {
		return identifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.identifier
	 * @param identifier  the value for core.task_metadata.identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.campaign_identifier
	 * @return  the value of core.task_metadata.campaign_identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public String getCampaignIdentifier() {
		return campaignIdentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.campaign_identifier
	 * @param campaignIdentifier  the value for core.task_metadata.campaign_identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setCampaignIdentifier(String campaignIdentifier) {
		this.campaignIdentifier = campaignIdentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.group_identifier
	 * @return  the value of core.task_metadata.group_identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public String getGroupIdentifier() {
		return groupIdentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.group_identifier
	 * @param groupIdentifier  the value for core.task_metadata.group_identifier
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setGroupIdentifier(String groupIdentifier) {
		this.groupIdentifier = groupIdentifier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.for_entity
	 * @return  the value of core.task_metadata.for_entity
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public String getForEntity() {
		return forEntity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.for_entity
	 * @param forEntity  the value for core.task_metadata.for_entity
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setForEntity(String forEntity) {
		this.forEntity = forEntity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column core.task_metadata.server_version
	 * @return  the value of core.task_metadata.server_version
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public Long getServerVersion() {
		return serverVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column core.task_metadata.server_version
	 * @param serverVersion  the value for core.task_metadata.server_version
	 * @mbg.generated  Fri Nov 09 12:47:47 EAT 2018
	 */
	public void setServerVersion(Long serverVersion) {
		this.serverVersion = serverVersion;
	}
}