# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Snapshot Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-SNAPSHOT
      - v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+-SNAPSHOT
      - v[0-9]+.[0-9]+.[0-9]+-[0-9a-zA-Z]+-[0-9a-zA-Z]+-SNAPSHOT
env: 
 NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
 NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }} 

      - uses: actions/checkout@v2
        with:
         submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Create multimedia dir
        run: sudo mkdir -p /opt/multimedia/patient_images && id

      - name: Grant read and write permissions to multimedia directory
        run: sudo chmod a+rwx /opt/multimedia/patient_images

     # - name: Run Unit tests with Maven
      #  run: mvn -B clean test --file pom.xml --no-transfer-progress  

      - name: Generate & upload library snapshot artifact JAR (Java Archive) file
        run: mvn clean deploy "-DsonatypeUsername=${{ secrets.NEXUS_USERNAME }}" "-DsonatypePassword=${{ secrets.NEXUS_PASSWORD }}"