name: Trivy Security Scan on OpenSRP-Server-Core repository
on:
  push:
    branches: 
      - trivy-ci-scan
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }} 
              
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode - SARIF
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-opensrp-client-core-repo-results.sarif'          

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-opensrp-client-core-repo-results.sarif'
