package org.opensrp.util.constants;

public interface ObsConstants {

    String CODED_FIELD_VALUE = "1065AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String NUMERIC_FIELD_CODE = "1639AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String ITN_CODED_FIELD_CODE = "159855AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String ITN_DATE_FIELD_CODE = "159432AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String VIT_A_CODED_FIELD_CODE = "161534AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    String DEWORMING_CODED_FIELD_CODE = "159922AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
}
